/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AttributeUpsertRequest"];
                    "text/json": components["schemas"]["AttributeUpsertRequest"];
                    "application/*+json": components["schemas"]["AttributeUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminAttributeDto"];
                        "application/json": components["schemas"]["AdminAttributeDto"];
                        "text/json": components["schemas"]["AdminAttributeDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/attributes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AttributeUpsertRequest"];
                    "text/json": components["schemas"]["AttributeUpsertRequest"];
                    "application/*+json": components["schemas"]["AttributeUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminAttributeDto"];
                        "application/json": components["schemas"]["AdminAttributeDto"];
                        "text/json": components["schemas"]["AdminAttributeDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminBrandDto"][];
                        "application/json": components["schemas"]["AdminBrandDto"][];
                        "text/json": components["schemas"]["AdminBrandDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BrandUpsertRequest"];
                    "text/json": components["schemas"]["BrandUpsertRequest"];
                    "application/*+json": components["schemas"]["BrandUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminBrandDto"];
                        "application/json": components["schemas"]["AdminBrandDto"];
                        "text/json": components["schemas"]["AdminBrandDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BrandUpsertRequest"];
                    "text/json": components["schemas"]["BrandUpsertRequest"];
                    "application/*+json": components["schemas"]["BrandUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminBrandDto"];
                        "application/json": components["schemas"]["AdminBrandDto"];
                        "text/json": components["schemas"]["AdminBrandDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminCategoryDto"][];
                        "application/json": components["schemas"]["AdminCategoryDto"][];
                        "text/json": components["schemas"]["AdminCategoryDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CategoryUpsertRequest"];
                    "text/json": components["schemas"]["CategoryUpsertRequest"];
                    "application/*+json": components["schemas"]["CategoryUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminCategoryDto"];
                        "application/json": components["schemas"]["AdminCategoryDto"];
                        "text/json": components["schemas"]["AdminCategoryDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CategoryUpsertRequest"];
                    "text/json": components["schemas"]["CategoryUpsertRequest"];
                    "application/*+json": components["schemas"]["CategoryUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminCategoryDto"];
                        "application/json": components["schemas"]["AdminCategoryDto"];
                        "text/json": components["schemas"]["AdminCategoryDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/{id}/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminAttributeDto"][];
                        "application/json": components["schemas"]["AdminAttributeDto"][];
                        "text/json": components["schemas"]["AdminAttributeDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    search?: string;
                    categoryId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminProductListItemDtoPagedResultDto"];
                        "application/json": components["schemas"]["AdminProductListItemDtoPagedResultDto"];
                        "text/json": components["schemas"]["AdminProductListItemDtoPagedResultDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProductUpsertRequest"];
                    "text/json": components["schemas"]["ProductUpsertRequest"];
                    "application/*+json": components["schemas"]["ProductUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminProductDetailDto"];
                        "application/json": components["schemas"]["AdminProductDetailDto"];
                        "text/json": components["schemas"]["AdminProductDetailDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminProductDetailDto"];
                        "application/json": components["schemas"]["AdminProductDetailDto"];
                        "text/json": components["schemas"]["AdminProductDetailDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProductUpsertRequest"];
                    "text/json": components["schemas"]["ProductUpsertRequest"];
                    "application/*+json": components["schemas"]["ProductUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminProductDetailDto"];
                        "application/json": components["schemas"]["AdminProductDetailDto"];
                        "text/json": components["schemas"]["AdminProductDetailDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/categories/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CategoryTreeDto"][];
                        "application/json": components["schemas"]["CategoryTreeDto"][];
                        "text/json": components["schemas"]["CategoryTreeDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/categories/{slug}/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CategoryFiltersDto"];
                        "application/json": components["schemas"]["CategoryFiltersDto"];
                        "text/json": components["schemas"]["CategoryFiltersDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/categories/{slug}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductListItemDtoPagedResultDto"];
                        "application/json": components["schemas"]["ProductListItemDtoPagedResultDto"];
                        "text/json": components["schemas"]["ProductListItemDtoPagedResultDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductDetailDto"];
                        "application/json": components["schemas"]["ProductDetailDto"];
                        "text/json": components["schemas"]["ProductDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductListItemDtoPagedResultDto"];
                        "application/json": components["schemas"]["ProductListItemDtoPagedResultDto"];
                        "text/json": components["schemas"]["ProductListItemDtoPagedResultDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminAttributeDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            categoryId?: string;
            name?: string | null;
            code?: string | null;
            type?: components["schemas"]["AttributeType"];
            options?: string[] | null;
            isFilterable?: boolean;
            isRequired?: boolean;
            filterWidget?: components["schemas"]["FilterWidget"];
            /** Format: int32 */
            sortOrder?: number;
        };
        AdminBrandDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            slug?: string | null;
            logoUrl?: string | null;
        };
        AdminCategoryDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            parentId?: string | null;
            name?: string | null;
            slug?: string | null;
            imageUrl?: string | null;
            /** Format: int32 */
            sortOrder?: number;
            isActive?: boolean;
            metaTitle?: string | null;
            metaDescription?: string | null;
        };
        AdminProductDetailDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            slug?: string | null;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            brandId?: string | null;
            description?: string | null;
            /** Format: double */
            price?: number;
            /** Format: double */
            salePrice?: number | null;
            /** Format: int32 */
            stock?: number;
            status?: components["schemas"]["ProductStatus"];
            images?: string[] | null;
            attributes?: {
                [key: string]: string;
            } | null;
            metaTitle?: string | null;
            metaDescription?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        AdminProductListItemDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            slug?: string | null;
            /** Format: uuid */
            categoryId?: string;
            categoryName?: string | null;
            /** Format: uuid */
            brandId?: string | null;
            brandName?: string | null;
            /** Format: double */
            price?: number;
            /** Format: double */
            salePrice?: number | null;
            /** Format: int32 */
            stock?: number;
            status?: components["schemas"]["ProductStatus"];
            imageUrl?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        AdminProductListItemDtoPagedResultDto: {
            items?: components["schemas"]["AdminProductListItemDto"][] | null;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        AttributeFilterDto: {
            code?: string | null;
            name?: string | null;
            type?: string | null;
            widget?: string | null;
            options?: components["schemas"]["FilterOptionDto"][] | null;
        };
        /** @enum {string} */
        AttributeType: "Select" | "MultiSelect" | "Number" | "Boolean" | "Text";
        AttributeUpsertRequest: {
            /** Format: uuid */
            categoryId?: string;
            name?: string | null;
            code?: string | null;
            type?: components["schemas"]["AttributeType"];
            options?: string[] | null;
            isFilterable?: boolean;
            isRequired?: boolean;
            filterWidget?: components["schemas"]["FilterWidget"];
            /** Format: int32 */
            sortOrder?: number;
        };
        BrandFilterDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            slug?: string | null;
            /** Format: int32 */
            count?: number;
        };
        BrandUpsertRequest: {
            name?: string | null;
            slug?: string | null;
            logoUrl?: string | null;
        };
        CategoryFiltersDto: {
            attributes?: components["schemas"]["AttributeFilterDto"][] | null;
            brands?: components["schemas"]["BrandFilterDto"][] | null;
            priceRange?: components["schemas"]["PriceRangeDto"];
        };
        CategoryTreeDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            slug?: string | null;
            imageUrl?: string | null;
            /** Format: int32 */
            sortOrder?: number;
            children?: components["schemas"]["CategoryTreeDto"][] | null;
        };
        CategoryUpsertRequest: {
            name?: string | null;
            slug?: string | null;
            /** Format: uuid */
            parentId?: string | null;
            imageUrl?: string | null;
            /** Format: int32 */
            sortOrder?: number;
            isActive?: boolean;
            metaTitle?: string | null;
            metaDescription?: string | null;
        };
        FilterOptionDto: {
            value?: string | null;
            /** Format: int32 */
            count?: number;
        };
        /** @enum {string} */
        FilterWidget: "Checkbox" | "Radio" | "Range";
        LoginRequest: {
            email?: string | null;
            password?: string | null;
        };
        PriceRangeDto: {
            /** Format: double */
            min?: number;
            /** Format: double */
            max?: number;
        };
        ProductAttributeDto: {
            name?: string | null;
            value?: string | null;
        };
        ProductDetailDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            slug?: string | null;
            description?: string | null;
            /** Format: double */
            price?: number;
            /** Format: double */
            salePrice?: number | null;
            /** Format: int32 */
            stock?: number;
            brandName?: string | null;
            categorySlug?: string | null;
            categoryName?: string | null;
            images?: string[] | null;
            attributes?: components["schemas"]["ProductAttributeDto"][] | null;
            metaTitle?: string | null;
            metaDescription?: string | null;
        };
        ProductListItemDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            slug?: string | null;
            /** Format: double */
            price?: number;
            /** Format: double */
            salePrice?: number | null;
            imageUrl?: string | null;
            brandName?: string | null;
            /** Format: int32 */
            stock?: number;
        };
        ProductListItemDtoPagedResultDto: {
            items?: components["schemas"]["ProductListItemDto"][] | null;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        /** @enum {string} */
        ProductStatus: "Draft" | "Active";
        ProductUpsertRequest: {
            name?: string | null;
            slug?: string | null;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            brandId?: string | null;
            description?: string | null;
            /** Format: double */
            price?: number;
            /** Format: double */
            salePrice?: number | null;
            /** Format: int32 */
            stock?: number;
            status?: components["schemas"]["ProductStatus"];
            images?: string[] | null;
            attributes?: {
                [key: string]: string;
            } | null;
            metaTitle?: string | null;
            metaDescription?: string | null;
        };
        RegisterRequest: {
            email?: string | null;
            password?: string | null;
            fullName?: string | null;
            phone?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
